// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id        int         `orm:"id,primary"      json:"id"`        //
	Type      int         `orm:"type"            json:"type"`      //
	Passport  string      `orm:"passport,unique" json:"passport"`  //
	Password  string      `orm:"password"        json:"password"`  //
	Email     string      `orm:"email"           json:"email"`     //
	Phone     string      `orm:"phone"           json:"phone"`     //
	Name      string      `orm:"name"            json:"name"`      //
	IsDeleted int         `orm:"is_deleted"      json:"isDeleted"` //
	CreateAt  *gtime.Time `orm:"create_at"       json:"createAt"`  //
	UpdateAt  *gtime.Time `orm:"update_at"       json:"updateAt"`  //
}
