// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfapp/app/model/internal"
)

// UserMail is the golang structure for table userMail.
type UserMail internal.UserMail

// Fill with you ideas below.
