// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gfapp/app/model/internal"

	"github.com/gogf/gf/frame/g"
)

// User is the golang structure for table user.
type User internal.User

// Fill with you ideas below.
// 登录请求参数，用于前后端交互参数格式约定
type UserApiLoginReq struct {
	Passport string `v:"required#账号不能为空"`
	Password string `v:"required#密码不能为空"`
	CaptchaReq
}

type UserServiceLoginReq struct {
	Passport string `json:"username"`
	Password string `json:"password"`
}

type UserApiUpdatePwdReq struct {
	Password  string `v:"required|length:6,16#请输入确认密码|密码长度应当在:min到:max之间"`
	Password2 string `v:"required|length:6,16|same:Password#密码不能为空|密码长度应当在:min到:max之间|两次密码输入不相等"`
}

type UserServiceUpdatePwdReq struct {
	Password  string `json:"password"`
	Password2 string
}

// 登录请求参数，用于前后端交互参数格式约定
type UserApiSignInWebReq struct {
	Username string `v:"required#账号不能为空" json:"username"`
	Password string `v:"required#密码不能为空" json:"password"`
}

type UserServiceSignInWebReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (r *UserServiceLoginReq) ToMap() (data *g.Map) {
	data = &g.Map{
		"passport":   r.Passport,
		"password":   r.Password,
		"is_deleted": 0,
	}
	return data
}

func (u *User) ToData() (data *g.Map) {
	data = &g.Map{
		"id":       u.Id,
		"type":     u.Type,
		"passport": u.Passport,
		"email":    u.Email,
		"phone":    u.Phone,
		"name":     u.Name,
	}
	return data
}
