# HTTP Server
[server]
	Address     = ":8299"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "/tmp/log/gf-app/server"

# Logger.
[logger]
    Path        = "/tmp/log/gf-app"
    Level       = "all"
    Stdout      = false
[logger.debug]
    path   = "/tmp/log/gf-app/debug"
    level  = "dev"
    stdout = false
[logger.test]
path   = "/tmp/log/gf-app/test"
level  = "info"
stdout = false

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
#     Delimiters  =  ["${", "}"]

[upload]
IndexFoldersEnabled = true
FileServerEnabled = true
url = "/file/upload"
link = "http://0.0.0.0:8080/file/upload"
dir = "/tmp/upload"
# Database.
[database]
    link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
    debug = true
    # Database logger.
[database.logger]
    Path   = "/tmp/log/gf-app/sql"
    Level  = "all"
    Stdout = true
# gf gen mode/dao
[gfcli]
# 根据配置的test数据库中的user/post表生成dao文件
[[gfcli.gen.dao]]
    link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
    tables = "user,post"
# 根据配置的test数据库中的user/post表生成model文件
[[gfcli.gen.model]]
    link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
    tables = "user,post"
[gfcli.build]
name = "main"
arch = "amd64"
system = "linux"
mod = "none"
cgo = 0
pack = ""
version = "0.1.9.0"
output = "./bin"
extra = ""

# Redis数据库配置
[redis]
    default = "127.0.0.1:6379,0"
    cache   = "127.0.0.1:6379,1,123456?idleTimeout=600"

# captcha configuration
[captcha]
key-long = 6
image-width = 240
image-height = 80
captcha-in-redis = false

[jwt]
salt    = "mapsalt"
exp     = 604800  # 单位s(60*60*24*7)