// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gfapp/app/dao/internal"
)

// userMailDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type userMailDao struct {
	internal.UserMailDao
}

var (
	// UserMail is globally public accessible object for table userMail operations.
	UserMail = userMailDao{
		internal.UserMail,
	}
)

// Fill with you ideas below.
